version: "3.6"

services:
  ngnode-fullstack:
    image: ngnode-fullstack
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - 5005:5005
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
