version: '3.6'

services:
  ngnode-fullstack:
    image: ngnode-fullstack
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 5050:5050
      - 9229:9229
    ## set your startup file here
    command: nodemon
