version: "3.6"

services:
  ngnode-fullstack:
    image: ngnode-fullstack
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5005:5005
      - 9229:9229
    ## set your startup file here
    command:
      - npm
      - run
      - dev
